
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRLIT = 47;
  public static final int PLUSPLUS = 24;
  public static final int DIVIDE = 32;
  public static final int CHAR = 13;
  public static final int EQUALS = 41;
  public static final int NOTEQUAL = 36;
  public static final int GREATER = 37;
  public static final int SEMI = 5;
  public static final int INT = 12;
  public static final int LESS = 38;
  public static final int MINUS = 30;
  public static final int CLOSEPAREN = 9;
  public static final int AND = 40;
  public static final int INTLIT = 45;
  public static final int OPENPAREN = 8;
  public static final int LESSEQUAL = 35;
  public static final int OR = 39;
  public static final int BOOL = 14;
  public static final int COMMA = 16;
  public static final int CLASS = 2;
  public static final int EQUALEQUAL = 33;
  public static final int PLUS = 29;
  public static final int MULTIPLY = 31;
  public static final int IF = 17;
  public static final int ID = 44;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 25;
  public static final int RETURN = 23;
  public static final int PRINTLINE = 22;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 7;
  public static final int VOID = 11;
  public static final int FLOATLIT = 48;
  public static final int GREATEREQUAL = 34;
  public static final int CHARLIT = 46;
  public static final int COLON = 43;
  public static final int ELSE = 18;
  public static final int OPENBRACKET = 6;
  public static final int READ = 20;
  public static final int FINAL = 10;
  public static final int WHILE = 19;
  public static final int CLOSEBRACE = 4;
  public static final int SQUIGGLY = 28;
  public static final int FLOAT = 15;
  public static final int OPENBRACE = 3;
  public static final int QUESTION = 42;
  public static final int FALSE = 27;
  public static final int PRINT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "OPENBRACE",
  "CLOSEBRACE",
  "SEMI",
  "OPENBRACKET",
  "CLOSEBRACKET",
  "OPENPAREN",
  "CLOSEPAREN",
  "FINAL",
  "VOID",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "COMMA",
  "IF",
  "ELSE",
  "WHILE",
  "READ",
  "PRINT",
  "PRINTLINE",
  "RETURN",
  "PLUSPLUS",
  "MINUSMINUS",
  "TRUE",
  "FALSE",
  "SQUIGGLY",
  "PLUS",
  "MINUS",
  "MULTIPLY",
  "DIVIDE",
  "EQUALEQUAL",
  "GREATEREQUAL",
  "LESSEQUAL",
  "NOTEQUAL",
  "GREATER",
  "LESS",
  "OR",
  "AND",
  "EQUALS",
  "QUESTION",
  "COLON",
  "ID",
  "INTLIT",
  "CHARLIT",
  "STRLIT",
  "FLOATLIT"
  };
}

